import { Platform, StyleSheet } from "react-native";
import {
  GRAY_DARK,
  GRAY_LIGHT,
  GRAY_MEDIUM,
  GRAY_STRONG,
  LIGHT_GRAY_BG,
  TEXT_COLOR,
  WHITE,
} from "../../util/colors";
import { normal3, regular, smallText, verySmallText } from "../fonts";

const styles = StyleSheet.create({
  topLocation: {
    flexDirection: "row",
    flex: 1,
    overflow: "hidden",
    flexWrap: "wrap",
  },
  plane: {
    display: "flex",
    backgroundColor: LIGHT_GRAY_BG,
    borderRadius: 10,
    borderWidth: 0.3,
    flexDirection: "row",
    borderColor: GRAY_MEDIUM,
    alignItems: "center",
  },
  airline: {
    fontSize: verySmallText,
    fontFamily: regular,
    fontStyle: "normal",
    textAlign: "center",
    color: GRAY_DARK,
  },
  flightTypeText: {
    fontSize: verySmallText,
    fontFamily: regular,
    fontStyle: "normal",
    color: GRAY_DARK,
  },
  layoverContainer: {
    backgroundColor: GRAY_LIGHT,
    alignSelf: "center",
    width: "90%",
    alignItems: "center",
    flexDirection: "row",
    padding: 10,
  },
  layover: {
    fontSize: smallText,
    fontFamily: regular,
    fontStyle: "normal",
    color: WHITE,
  },
  mainTerminals: {
    margin: 2,
    fontSize: smallText,
    fontFamily: regular,
    fontStyle: "normal",
    color: GRAY_DARK,
  },
  mainTime: {
    margin: 2,
    fontSize: normal3,
    fontFamily: regular,
    fontStyle: "normal",
    color: TEXT_COLOR,
  },
  date: {
    fontSize: verySmallText,
    marginHorizontal: 4,
    fontFamily: regular,
    fontStyle: "normal",
    color: GRAY_DARK,
  },
  location: {
    margin: 5,
    fontSize: smallText,
    fontFamily: regular,
    fontStyle: "normal",
    color: TEXT_COLOR,
  },
  totalTime: {
    margin: 5,
    fontSize: smallText,
    fontFamily: regular,
    fontStyle: "normal",
    color: GRAY_DARK,
  },
  imageStyle: {
    backgroundColor: WHITE,
    marginHorizontal: 10,
    borderRadius: 12.5,
    width: 25,
    resizeMode: Platform.OS == "ios" ? "contain" : "cover",
    borderWidth: 1,
    borderColor: GRAY_MEDIUM,
    height: 25,
  },
  background: {
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    position: "absolute",
  },
  rootContainer: {
    display: "flex",
    flexDirection: "row",
    marginHorizontal: 12,
    justifyContent: "space-between",
    alignSelf: "center",
  },
  container: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    borderWidth: 0.5,
    borderColor: GRAY_MEDIUM,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingBottom: 10,
    backgroundColor: WHITE,
  },
  seperator: {
    backgroundColor: GRAY_STRONG,
    alignSelf: "center",
    width: "90%",
    marginVertical: 20,
    height: 1,
  },
  flightType: {
    alignSelf: "center",
    backgroundColor: LIGHT_GRAY_BG,
    paddingHorizontal: 5,
    paddingVertical: 2,
    borderColor: GRAY_MEDIUM,
    alignItems: "center",
    borderBottomWidth: 0.5,
    borderEndWidth: 0.5,
    borderLeftWidth: 0.5,
  },
});

export default styles;
