import { StyleSheet } from "react-native";
import {
  GRAY_DARK,
  GRAY_LIGHT,
  GRAY_MEDIUM,
  PRIMARY,
  PRIMARY_DARK,
  TEXT_COLOR,
  WHITE,
} from "../../../util/colors";
import {
  extralargeText,
  largeText,
  normal3,
  normal4,
  regular,
  verySmallText,
} from "../../../util/fonts";

const styles = StyleSheet.create({
  topViewRoot: {
    width: "100%",
    height: 110,
  },
  DateViewRoot: {
    flex: 1,
    height: 85,
  },
  Divider: {
    position: "absolute",
    top: 0,
    bottom: 0,
    justifyContent: "center",
    alignSelf: "center",
    alignItems: "center",
  },
  locationDivider: {
    width: 1,
    height: "100%",
    backgroundColor: GRAY_MEDIUM,
    position: "absolute",
  },
  halftopViewRoot: {
    width: "100%",
    height: "50%",
    position: "absolute",
    top: 0,
    backgroundColor: PRIMARY,
  },
  topViewWrapper: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    justifyContent: "center",
    backgroundColor: WHITE,
    alignItems: "center",
    height: 130,
    borderRadius: 65,
    marginHorizontal: 10,
    borderWidth: 1,
    borderColor: GRAY_MEDIUM,
  },
  time: {
    margin: 5,
    fontSize: verySmallText,
    fontFamily: regular,
    fontStyle: "normal",
    color: GRAY_LIGHT,
  },
  dateTime: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  flightView: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  chipGroup: {
    paddingHorizontal: 15,
    paddingTop: 40,
    paddingBottom: 20,
    backgroundColor: PRIMARY,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  mainTime: {
    margin: 2,
    fontSize: normal3,
    fontFamily: regular,
    fontStyle: "normal",
    fontWeight: "400",
    color: TEXT_COLOR,
  },
  mainTimeBottom: {
    margin: 2,
    fontSize: normal4,
    fontFamily: regular,
    fontStyle: "normal",
    fontWeight: "300",
    color: GRAY_DARK,
  },
  flight: {
    margin: 2,
    fontSize: extralargeText,
    fontFamily: regular,
    fontStyle: "normal",
    fontWeight: "300",
    color: TEXT_COLOR,
  },
  date: {
    fontSize: verySmallText,
    fontFamily: regular,
    fontStyle: "normal",
    color: GRAY_DARK,
  },
  background: {
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    position: "absolute",
  },
  container: {
    display: "flex",
    flexDirection: "row",
    borderRadius: 20,
    marginVertical: 8,
    alignSelf: "center",
  },
  PrimaryButtonContainer: {
    paddingVertical: 0,
    paddingHorizontal: 0,
    marginVertical: 30,
    paddingLeft: 20,
    borderColor: PRIMARY_DARK,
    borderWidth: 1,
  },
  PrimaryButtonContainerText: {
    color: WHITE,
    fontSize: largeText,
    fontWeight: "300",
    paddingHorizontal: 20,
  },
  artwork: {
    width: "98%",
    height: 200,
    alignSelf: "center",
    resizeMode: "contain",
    position: "absolute",
    bottom: 0,
  },
});

export default styles;
